Microverse Module 1 Portfolio pair programming project: Data store in browser
binyamolango/Personal-Portfolio pull request #20
Opened 2023-06-30 09:13 UTC by binyamolango

# Hello Reviewer 👋

> Here are the changes that we implemented

- Created a single JavaScript object with all the data from the entire form and saved it in local storage.
- When the user changes the content of any input field, the data is saved to the local storage.
- When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.

2023-06-30 11:23 UTC, Alusp requested changes
Hi @binyamolango, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
 
![close](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Highlights
- [ ] Good Commit History :green_circle: 
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
- [ ] No Linter Errors :green_circle: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 11:23 UTC, Alusp commented on script-preserveData.js
> +document.getElementById('msg').value = formObj.text;
- [ ] Good job far, :clap: However, Your form data send data using `formspree` but does not save data in the broswer's `Localstorage`, and also, your page does not persist data on the form when `refreshed or reloaded`

Please check your `script-preservedData.js` file and ensure that it is imported correctly in your `index.html` file :slightly_smiling_face: 

Below is a screenshot of your site: :arrow_down: 

![Student Data](https://github.com/binyamolango/Personal-Portfolio/assets/43528594/db3ce028-3422-46d4-9235-9df7c29c945d)

2023-06-30 12:03 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @binyamolango   :wave:

## Highlights :1st_place_medal:


✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 12:03 UTC, Cabraham1 commented on script-validation.js
> +form.addEventListener('submit', emailValidation);
- [ ] Good job so far! However, your form data is sent using Formspree but does not save data in the browser's LocalStorage. Additionally, your page does not persist data on the form when refreshed or reloaded.

To address these issues, please check your script-preservedData.js file and ensure that it is imported correctly in your index.html file.

I would also like to suggest using LocalStorage to save the form data in the browser. By utilizing LocalStorage, you can store the data locally and retrieve it even after the page is refreshed or reloaded.

To implement this, you can modify your script-preservedData.js file to include the necessary code for interacting with LocalStorage. You can use the localStorage.setItem() method to store the form data and localStorage.getItem() method to retrieve it.

Here's an example of how you can save the form data to LocalStorage:

Retrieve form data
const formData = {
  // Your form data here
};

Save form data to LocalStorage
localStorage.setItem('formData', JSON.stringify(formData));

And here's how you can retrieve the saved data from LocalStorage:

Retrieve form data from LocalStorage
const savedData = localStorage.getItem('formData');

if (savedData) {
  const formData = JSON.parse(savedData);
  // Populate the form fields with formData
}

By implementing LocalStorage in your script, you can ensure that the form data persists across page refreshes or reloads.

2023-07-01 20:00 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @binyamolango, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## To Highlight 👍

- Descriptive Pull Request title and summary. ✔️
- Preserve data in the LocalStorage ✔️ 
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 20:03 UTC, merged